services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
      - MEDIA_BASE_PATH=/path/to/media
    volumes:
      - jellyfin_config:/config
      - ${MEDIA_BASE_PATH}/tvshows:/data/tvshows
      - ${MEDIA_BASE_PATH}/movies:/data/movies
      - ${MEDIA_BASE_PATH}/animes:/data/animes
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
volumes:
  jellyfin_config: null
networks: {}
